name: Test CRA Template
on: [push]

jobs:
  test-cra-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Required to mount the Github Workspace to a volume
      - uses: addnab/docker-run-action@v3
        with:
          image: node:lts-gallium
          options: -v ${{ github.workspace }}:/github-workspace
          run: |
            echo "Running Test Script"
            /github-workspace/test-cra.sh
